# Generated by Django 3.0 on 2021-01-31 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20210131_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='group',
        ),
    ]
